name: 'CI'

on:
  pull_request:
    branches: [ _main ]

jobs:
    Coverage_Report:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [16.x]

        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              id: coverage
              with:
                  output: report-markdown
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  annotations: none
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: ${{ steps.coverage.outputs.report }}
